---

galaxy_info:
  author: Veros Kaplan <verosk@noreply.users.github.com>
  description: Ansible Role for Docker Installation.
  company: N/A
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - system
    - docker
dependencies: []
