---
- name: Ensure gpg (required for apt-key)
  apt:
    name: gpg
    state: present
  when: docker_add_repository and ansible_os_family == 'Debian'

- name: Add apt repository key
  apt_key:
    id: "{{ item.key_id }}"
    url: "{{ item.key_url }}"
    state: "{{ item.state|default('present') }}"
  with_items: '{{ docker_apt_repository }}'
  when: docker_add_repository and ansible_os_family == 'Debian'

- name: Add apt repository
  apt_repository:
    repo: "{{ item.repository_url }}"
    state: "{{ item.state|default('present') }}"
  with_items: '{{ docker_apt_repository }}'
  when: docker_add_repository and ansible_os_family == 'Debian'
